apiVersion: v1
kind: Service
metadata:
  name: springbootapp
  labels:
    app: springbootapp
spec:
  ports:
    - port: 80
  selector:
    app: springbootapp
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: springbootapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp
  labels:
    app: springbootapp
spec:
  selector:
    matchLabels:
      app: springbootapp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: springbootapp
        tier: frontend
    spec:
      containers:
      - image: ktchowdary4/springbootapp
        name: springbootapp
        env:
        - name: DATABASE_HOST
          value: springbootapp-mysql
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: DATABASE_USER
          value: root
        - name: DATABASE_NAME
          value: notes_app
        - name: DATABASE_PORT
          value: "3306"
        ports:
        - containerPort: 8080
          name: springbootapp
        volumeMounts:
        - name: springbootapp-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: springbootapp-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim

